CC=		clang
DESTDIR?=       ""
BIN_PATH=	BIN_PATH_VAL
MAN_PATH=	MAN_PATH_VAL


default: realpath

realpath: realpath.c
	$(CC) -o realpath realpath.c -Werror -Wextra

clean:
	rm -f realpath
	rm -fr test_files_*

test:
	./test.sh

install:
	install realpath $(DESTDIR)$(BIN_PATH)
	install -m 0644 realpath.1 $(DESTDIR)$(MAN_PATH)

