.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "REALPATH" "1" "September 2014" "" ""
.
.SH "NAME"
\fBrealpath\fR \- return resolved physical path
.
.P
This document created by ron\. http://rtomayko\.github\.io/ronn/ronn\.1\.html#EXAMPLES
.
.P
http://www\.cyberciti\.biz/faq/linux\-unix\-creating\-a\-manpage/
.
.P
ronn \-\-pipe \-\-roff README\.md > realpath\.1
